export enum ButtonStyle {
  ADD_TASK = 'add-task',
  ADD_COLUMN = 'add-column',
  ADD_COLUMN_EMPTY_BOARD = 'add-column-empty-board',
  ACTIVE_BOARD = 'active-board',
  BOARDS_MOBILE = 'boards-mobile',
  CREATE_BOARD = 'create-board',
  FORM_PRIMARY = 'form-primary',
  FORM_SECONDARY = 'form-secondary',
  FORM_WARNING = 'form-warning',
  HIDE_SIDEBAR = 'hide-sidebar',
  POPUP = 'popup',
  SELECT_BOARD = 'select-board',
  SHOW_SIDEBAR = 'show-sidebar',
  TEXT_PRIMARY = 'text-primary',
  TEXT_WARNING = 'text-warning',
  TOGGLE = 'toggle',
}
