export type btnStyle =
  | 'add-task'
  | 'form-primary'
  | 'form-secondary'
  | 'form-warning'
  | 'select-board'
  | 'active-board'
  | 'create-board'
  | 'hide-sidebar'
  | 'text-primary'
  | 'text-warning'
  | 'add-column'
  | 'popup'
  | 'show-sidebar'
  | 'toggle';
